# Generated by Django 6.0.2 on 2026-02-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videolike'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='num_of_dislikes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
